marttiphpbb_extrajavascript_render_controller:
    pattern: /extrajavascript/{id}__js
    defaults: { _controller: marttiphpbb.extrajavascript.controller:render }
    requirements:
        _method: GET
        id: '[a-z][a-z0-9-]+'
